/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aresibo.avro.alert.common;
@org.apache.avro.specific.AvroGenerated
public enum Level implements org.apache.avro.generic.GenericEnumSymbol<Level> {
  LOW, MEDIUM, HIGH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Level\",\"namespace\":\"com.aresibo.avro.alert.common\",\"symbols\":[\"LOW\",\"MEDIUM\",\"HIGH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
