/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aresibo.avro.alert.risk;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CiramDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 274931540592298331L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CiramDetails\",\"namespace\":\"com.aresibo.avro.alert.risk\",\"fields\":[{\"name\":\"impact\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"Level\",\"namespace\":\"com.aresibo.avro.alert.common\",\"symbols\":[\"LOW\",\"MEDIUM\",\"HIGH\"]}]},{\"name\":\"threat\",\"type\":[\"null\",\"com.aresibo.avro.alert.common.Level\"]},{\"name\":\"vulnerability\",\"type\":[\"null\",\"com.aresibo.avro.alert.common.Level\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CiramDetails> ENCODER =
      new BinaryMessageEncoder<CiramDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CiramDetails> DECODER =
      new BinaryMessageDecoder<CiramDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CiramDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CiramDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CiramDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CiramDetails>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CiramDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CiramDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CiramDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CiramDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   public com.aresibo.avro.alert.common.Level impact;
   public com.aresibo.avro.alert.common.Level threat;
   public com.aresibo.avro.alert.common.Level vulnerability;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CiramDetails() {}

  /**
   * All-args constructor.
   * @param impact The new value for impact
   * @param threat The new value for threat
   * @param vulnerability The new value for vulnerability
   */
  public CiramDetails(com.aresibo.avro.alert.common.Level impact, com.aresibo.avro.alert.common.Level threat, com.aresibo.avro.alert.common.Level vulnerability) {
    this.impact = impact;
    this.threat = threat;
    this.vulnerability = vulnerability;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return impact;
    case 1: return threat;
    case 2: return vulnerability;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: impact = (com.aresibo.avro.alert.common.Level)value$; break;
    case 1: threat = (com.aresibo.avro.alert.common.Level)value$; break;
    case 2: vulnerability = (com.aresibo.avro.alert.common.Level)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'impact' field.
   * @return The value of the 'impact' field.
   */
  public com.aresibo.avro.alert.common.Level getImpact() {
    return impact;
  }


  /**
   * Sets the value of the 'impact' field.
   * @param value the value to set.
   */
  public void setImpact(com.aresibo.avro.alert.common.Level value) {
    this.impact = value;
  }

  /**
   * Gets the value of the 'threat' field.
   * @return The value of the 'threat' field.
   */
  public com.aresibo.avro.alert.common.Level getThreat() {
    return threat;
  }


  /**
   * Sets the value of the 'threat' field.
   * @param value the value to set.
   */
  public void setThreat(com.aresibo.avro.alert.common.Level value) {
    this.threat = value;
  }

  /**
   * Gets the value of the 'vulnerability' field.
   * @return The value of the 'vulnerability' field.
   */
  public com.aresibo.avro.alert.common.Level getVulnerability() {
    return vulnerability;
  }


  /**
   * Sets the value of the 'vulnerability' field.
   * @param value the value to set.
   */
  public void setVulnerability(com.aresibo.avro.alert.common.Level value) {
    this.vulnerability = value;
  }

  /**
   * Creates a new CiramDetails RecordBuilder.
   * @return A new CiramDetails RecordBuilder
   */
  public static com.aresibo.avro.alert.risk.CiramDetails.Builder newBuilder() {
    return new com.aresibo.avro.alert.risk.CiramDetails.Builder();
  }

  /**
   * Creates a new CiramDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CiramDetails RecordBuilder
   */
  public static com.aresibo.avro.alert.risk.CiramDetails.Builder newBuilder(com.aresibo.avro.alert.risk.CiramDetails.Builder other) {
    if (other == null) {
      return new com.aresibo.avro.alert.risk.CiramDetails.Builder();
    } else {
      return new com.aresibo.avro.alert.risk.CiramDetails.Builder(other);
    }
  }

  /**
   * Creates a new CiramDetails RecordBuilder by copying an existing CiramDetails instance.
   * @param other The existing instance to copy.
   * @return A new CiramDetails RecordBuilder
   */
  public static com.aresibo.avro.alert.risk.CiramDetails.Builder newBuilder(com.aresibo.avro.alert.risk.CiramDetails other) {
    if (other == null) {
      return new com.aresibo.avro.alert.risk.CiramDetails.Builder();
    } else {
      return new com.aresibo.avro.alert.risk.CiramDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for CiramDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CiramDetails>
    implements org.apache.avro.data.RecordBuilder<CiramDetails> {

    private com.aresibo.avro.alert.common.Level impact;
    private com.aresibo.avro.alert.common.Level threat;
    private com.aresibo.avro.alert.common.Level vulnerability;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.aresibo.avro.alert.risk.CiramDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.impact)) {
        this.impact = data().deepCopy(fields()[0].schema(), other.impact);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.threat)) {
        this.threat = data().deepCopy(fields()[1].schema(), other.threat);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.vulnerability)) {
        this.vulnerability = data().deepCopy(fields()[2].schema(), other.vulnerability);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CiramDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.aresibo.avro.alert.risk.CiramDetails other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.impact)) {
        this.impact = data().deepCopy(fields()[0].schema(), other.impact);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.threat)) {
        this.threat = data().deepCopy(fields()[1].schema(), other.threat);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.vulnerability)) {
        this.vulnerability = data().deepCopy(fields()[2].schema(), other.vulnerability);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'impact' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.common.Level getImpact() {
      return impact;
    }


    /**
      * Sets the value of the 'impact' field.
      * @param value The value of 'impact'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder setImpact(com.aresibo.avro.alert.common.Level value) {
      validate(fields()[0], value);
      this.impact = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'impact' field has been set.
      * @return True if the 'impact' field has been set, false otherwise.
      */
    public boolean hasImpact() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'impact' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder clearImpact() {
      impact = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'threat' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.common.Level getThreat() {
      return threat;
    }


    /**
      * Sets the value of the 'threat' field.
      * @param value The value of 'threat'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder setThreat(com.aresibo.avro.alert.common.Level value) {
      validate(fields()[1], value);
      this.threat = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'threat' field has been set.
      * @return True if the 'threat' field has been set, false otherwise.
      */
    public boolean hasThreat() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'threat' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder clearThreat() {
      threat = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'vulnerability' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.common.Level getVulnerability() {
      return vulnerability;
    }


    /**
      * Sets the value of the 'vulnerability' field.
      * @param value The value of 'vulnerability'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder setVulnerability(com.aresibo.avro.alert.common.Level value) {
      validate(fields()[2], value);
      this.vulnerability = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'vulnerability' field has been set.
      * @return True if the 'vulnerability' field has been set, false otherwise.
      */
    public boolean hasVulnerability() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'vulnerability' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder clearVulnerability() {
      vulnerability = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CiramDetails build() {
      try {
        CiramDetails record = new CiramDetails();
        record.impact = fieldSetFlags()[0] ? this.impact : (com.aresibo.avro.alert.common.Level) defaultValue(fields()[0]);
        record.threat = fieldSetFlags()[1] ? this.threat : (com.aresibo.avro.alert.common.Level) defaultValue(fields()[1]);
        record.vulnerability = fieldSetFlags()[2] ? this.vulnerability : (com.aresibo.avro.alert.common.Level) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CiramDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<CiramDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CiramDetails>
    READER$ = (org.apache.avro.io.DatumReader<CiramDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.impact == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.impact.ordinal());
    }

    if (this.threat == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.threat.ordinal());
    }

    if (this.vulnerability == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.vulnerability.ordinal());
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.impact = null;
      } else {
        this.impact = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.threat = null;
      } else {
        this.threat = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.vulnerability = null;
      } else {
        this.vulnerability = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.impact = null;
          } else {
            this.impact = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.threat = null;
          } else {
            this.threat = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.vulnerability = null;
          } else {
            this.vulnerability = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










