/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aresibo.avro.alert.risk;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RiskAlert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5696365226349384631L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RiskAlert\",\"namespace\":\"com.aresibo.avro.alert.risk\",\"fields\":[{\"name\":\"alert_id\",\"type\":\"int\"},{\"name\":\"alert_end_time\",\"type\":\"long\"},{\"name\":\"alert_start_time\",\"type\":\"long\"},{\"name\":\"alert_text\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"alert_title\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"tracked_entity_id\",\"type\":\"int\"},{\"name\":\"alert_level\",\"type\":{\"type\":\"enum\",\"name\":\"Level\",\"namespace\":\"com.aresibo.avro.alert.common\",\"symbols\":[\"LOW\",\"MEDIUM\",\"HIGH\"]}},{\"name\":\"alert_status\",\"type\":{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"com.aresibo.avro.alert.common\",\"symbols\":[\"ALERT_ACTIVE\",\"ALERT_INACTIVE\"]}},{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"namespace\":\"com.aresibo.avro.alert.common\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"Point\"},{\"name\":\"coordinates\",\"type\":[{\"type\":\"array\",\"items\":[{\"type\":\"record\",\"name\":\"Point\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\",\"default\":0.0},{\"name\":\"longitude\",\"type\":\"double\",\"default\":0.0}]},\"null\"]},\"null\"]},{\"name\":\"radius\",\"type\":\"float\",\"default\":0.0}]}},{\"name\":\"ciram_details\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"CiramDetails\",\"fields\":[{\"name\":\"impact\",\"type\":[\"null\",\"com.aresibo.avro.alert.common.Level\"]},{\"name\":\"threat\",\"type\":[\"null\",\"com.aresibo.avro.alert.common.Level\"]},{\"name\":\"vulnerability\",\"type\":[\"null\",\"com.aresibo.avro.alert.common.Level\"]}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RiskAlert> ENCODER =
      new BinaryMessageEncoder<RiskAlert>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RiskAlert> DECODER =
      new BinaryMessageDecoder<RiskAlert>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RiskAlert> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RiskAlert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RiskAlert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RiskAlert>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RiskAlert to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RiskAlert from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RiskAlert instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RiskAlert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   public int alert_id;
   public long alert_end_time;
   public long alert_start_time;
   public java.lang.String alert_text;
   public java.lang.String alert_title;
   public long timestamp;
   public int tracked_entity_id;
   public com.aresibo.avro.alert.common.Level alert_level;
   public com.aresibo.avro.alert.common.Status alert_status;
   public com.aresibo.avro.alert.common.Location location;
   public com.aresibo.avro.alert.risk.CiramDetails ciram_details;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RiskAlert() {}

  /**
   * All-args constructor.
   * @param alert_id The new value for alert_id
   * @param alert_end_time The new value for alert_end_time
   * @param alert_start_time The new value for alert_start_time
   * @param alert_text The new value for alert_text
   * @param alert_title The new value for alert_title
   * @param timestamp The new value for timestamp
   * @param tracked_entity_id The new value for tracked_entity_id
   * @param alert_level The new value for alert_level
   * @param alert_status The new value for alert_status
   * @param location The new value for location
   * @param ciram_details The new value for ciram_details
   */
  public RiskAlert(java.lang.Integer alert_id, java.lang.Long alert_end_time, java.lang.Long alert_start_time, java.lang.String alert_text, java.lang.String alert_title, java.lang.Long timestamp, java.lang.Integer tracked_entity_id, com.aresibo.avro.alert.common.Level alert_level, com.aresibo.avro.alert.common.Status alert_status, com.aresibo.avro.alert.common.Location location, com.aresibo.avro.alert.risk.CiramDetails ciram_details) {
    this.alert_id = alert_id;
    this.alert_end_time = alert_end_time;
    this.alert_start_time = alert_start_time;
    this.alert_text = alert_text;
    this.alert_title = alert_title;
    this.timestamp = timestamp;
    this.tracked_entity_id = tracked_entity_id;
    this.alert_level = alert_level;
    this.alert_status = alert_status;
    this.location = location;
    this.ciram_details = ciram_details;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return alert_id;
    case 1: return alert_end_time;
    case 2: return alert_start_time;
    case 3: return alert_text;
    case 4: return alert_title;
    case 5: return timestamp;
    case 6: return tracked_entity_id;
    case 7: return alert_level;
    case 8: return alert_status;
    case 9: return location;
    case 10: return ciram_details;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: alert_id = (java.lang.Integer)value$; break;
    case 1: alert_end_time = (java.lang.Long)value$; break;
    case 2: alert_start_time = (java.lang.Long)value$; break;
    case 3: alert_text = value$ != null ? value$.toString() : null; break;
    case 4: alert_title = value$ != null ? value$.toString() : null; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    case 6: tracked_entity_id = (java.lang.Integer)value$; break;
    case 7: alert_level = (com.aresibo.avro.alert.common.Level)value$; break;
    case 8: alert_status = (com.aresibo.avro.alert.common.Status)value$; break;
    case 9: location = (com.aresibo.avro.alert.common.Location)value$; break;
    case 10: ciram_details = (com.aresibo.avro.alert.risk.CiramDetails)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'alert_id' field.
   * @return The value of the 'alert_id' field.
   */
  public int getAlertId() {
    return alert_id;
  }


  /**
   * Sets the value of the 'alert_id' field.
   * @param value the value to set.
   */
  public void setAlertId(int value) {
    this.alert_id = value;
  }

  /**
   * Gets the value of the 'alert_end_time' field.
   * @return The value of the 'alert_end_time' field.
   */
  public long getAlertEndTime() {
    return alert_end_time;
  }


  /**
   * Sets the value of the 'alert_end_time' field.
   * @param value the value to set.
   */
  public void setAlertEndTime(long value) {
    this.alert_end_time = value;
  }

  /**
   * Gets the value of the 'alert_start_time' field.
   * @return The value of the 'alert_start_time' field.
   */
  public long getAlertStartTime() {
    return alert_start_time;
  }


  /**
   * Sets the value of the 'alert_start_time' field.
   * @param value the value to set.
   */
  public void setAlertStartTime(long value) {
    this.alert_start_time = value;
  }

  /**
   * Gets the value of the 'alert_text' field.
   * @return The value of the 'alert_text' field.
   */
  public java.lang.String getAlertText() {
    return alert_text;
  }


  /**
   * Sets the value of the 'alert_text' field.
   * @param value the value to set.
   */
  public void setAlertText(java.lang.String value) {
    this.alert_text = value;
  }

  /**
   * Gets the value of the 'alert_title' field.
   * @return The value of the 'alert_title' field.
   */
  public java.lang.String getAlertTitle() {
    return alert_title;
  }


  /**
   * Sets the value of the 'alert_title' field.
   * @param value the value to set.
   */
  public void setAlertTitle(java.lang.String value) {
    this.alert_title = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'tracked_entity_id' field.
   * @return The value of the 'tracked_entity_id' field.
   */
  public int getTrackedEntityId() {
    return tracked_entity_id;
  }


  /**
   * Sets the value of the 'tracked_entity_id' field.
   * @param value the value to set.
   */
  public void setTrackedEntityId(int value) {
    this.tracked_entity_id = value;
  }

  /**
   * Gets the value of the 'alert_level' field.
   * @return The value of the 'alert_level' field.
   */
  public com.aresibo.avro.alert.common.Level getAlertLevel() {
    return alert_level;
  }


  /**
   * Sets the value of the 'alert_level' field.
   * @param value the value to set.
   */
  public void setAlertLevel(com.aresibo.avro.alert.common.Level value) {
    this.alert_level = value;
  }

  /**
   * Gets the value of the 'alert_status' field.
   * @return The value of the 'alert_status' field.
   */
  public com.aresibo.avro.alert.common.Status getAlertStatus() {
    return alert_status;
  }


  /**
   * Sets the value of the 'alert_status' field.
   * @param value the value to set.
   */
  public void setAlertStatus(com.aresibo.avro.alert.common.Status value) {
    this.alert_status = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public com.aresibo.avro.alert.common.Location getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(com.aresibo.avro.alert.common.Location value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'ciram_details' field.
   * @return The value of the 'ciram_details' field.
   */
  public com.aresibo.avro.alert.risk.CiramDetails getCiramDetails() {
    return ciram_details;
  }


  /**
   * Sets the value of the 'ciram_details' field.
   * @param value the value to set.
   */
  public void setCiramDetails(com.aresibo.avro.alert.risk.CiramDetails value) {
    this.ciram_details = value;
  }

  /**
   * Creates a new RiskAlert RecordBuilder.
   * @return A new RiskAlert RecordBuilder
   */
  public static com.aresibo.avro.alert.risk.RiskAlert.Builder newBuilder() {
    return new com.aresibo.avro.alert.risk.RiskAlert.Builder();
  }

  /**
   * Creates a new RiskAlert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RiskAlert RecordBuilder
   */
  public static com.aresibo.avro.alert.risk.RiskAlert.Builder newBuilder(com.aresibo.avro.alert.risk.RiskAlert.Builder other) {
    if (other == null) {
      return new com.aresibo.avro.alert.risk.RiskAlert.Builder();
    } else {
      return new com.aresibo.avro.alert.risk.RiskAlert.Builder(other);
    }
  }

  /**
   * Creates a new RiskAlert RecordBuilder by copying an existing RiskAlert instance.
   * @param other The existing instance to copy.
   * @return A new RiskAlert RecordBuilder
   */
  public static com.aresibo.avro.alert.risk.RiskAlert.Builder newBuilder(com.aresibo.avro.alert.risk.RiskAlert other) {
    if (other == null) {
      return new com.aresibo.avro.alert.risk.RiskAlert.Builder();
    } else {
      return new com.aresibo.avro.alert.risk.RiskAlert.Builder(other);
    }
  }

  /**
   * RecordBuilder for RiskAlert instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RiskAlert>
    implements org.apache.avro.data.RecordBuilder<RiskAlert> {

    private int alert_id;
    private long alert_end_time;
    private long alert_start_time;
    private java.lang.String alert_text;
    private java.lang.String alert_title;
    private long timestamp;
    private int tracked_entity_id;
    private com.aresibo.avro.alert.common.Level alert_level;
    private com.aresibo.avro.alert.common.Status alert_status;
    private com.aresibo.avro.alert.common.Location location;
    private com.aresibo.avro.alert.common.Location.Builder locationBuilder;
    private com.aresibo.avro.alert.risk.CiramDetails ciram_details;
    private com.aresibo.avro.alert.risk.CiramDetails.Builder ciram_detailsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.aresibo.avro.alert.risk.RiskAlert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.alert_id)) {
        this.alert_id = data().deepCopy(fields()[0].schema(), other.alert_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.alert_end_time)) {
        this.alert_end_time = data().deepCopy(fields()[1].schema(), other.alert_end_time);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.alert_start_time)) {
        this.alert_start_time = data().deepCopy(fields()[2].schema(), other.alert_start_time);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.alert_text)) {
        this.alert_text = data().deepCopy(fields()[3].schema(), other.alert_text);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.alert_title)) {
        this.alert_title = data().deepCopy(fields()[4].schema(), other.alert_title);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.tracked_entity_id)) {
        this.tracked_entity_id = data().deepCopy(fields()[6].schema(), other.tracked_entity_id);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.alert_level)) {
        this.alert_level = data().deepCopy(fields()[7].schema(), other.alert_level);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.alert_status)) {
        this.alert_status = data().deepCopy(fields()[8].schema(), other.alert_status);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.location)) {
        this.location = data().deepCopy(fields()[9].schema(), other.location);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (other.hasLocationBuilder()) {
        this.locationBuilder = com.aresibo.avro.alert.common.Location.newBuilder(other.getLocationBuilder());
      }
      if (isValidValue(fields()[10], other.ciram_details)) {
        this.ciram_details = data().deepCopy(fields()[10].schema(), other.ciram_details);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (other.hasCiramDetailsBuilder()) {
        this.ciram_detailsBuilder = com.aresibo.avro.alert.risk.CiramDetails.newBuilder(other.getCiramDetailsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing RiskAlert instance
     * @param other The existing instance to copy.
     */
    private Builder(com.aresibo.avro.alert.risk.RiskAlert other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.alert_id)) {
        this.alert_id = data().deepCopy(fields()[0].schema(), other.alert_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alert_end_time)) {
        this.alert_end_time = data().deepCopy(fields()[1].schema(), other.alert_end_time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.alert_start_time)) {
        this.alert_start_time = data().deepCopy(fields()[2].schema(), other.alert_start_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.alert_text)) {
        this.alert_text = data().deepCopy(fields()[3].schema(), other.alert_text);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.alert_title)) {
        this.alert_title = data().deepCopy(fields()[4].schema(), other.alert_title);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.tracked_entity_id)) {
        this.tracked_entity_id = data().deepCopy(fields()[6].schema(), other.tracked_entity_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.alert_level)) {
        this.alert_level = data().deepCopy(fields()[7].schema(), other.alert_level);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.alert_status)) {
        this.alert_status = data().deepCopy(fields()[8].schema(), other.alert_status);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.location)) {
        this.location = data().deepCopy(fields()[9].schema(), other.location);
        fieldSetFlags()[9] = true;
      }
      this.locationBuilder = null;
      if (isValidValue(fields()[10], other.ciram_details)) {
        this.ciram_details = data().deepCopy(fields()[10].schema(), other.ciram_details);
        fieldSetFlags()[10] = true;
      }
      this.ciram_detailsBuilder = null;
    }

    /**
      * Gets the value of the 'alert_id' field.
      * @return The value.
      */
    public int getAlertId() {
      return alert_id;
    }


    /**
      * Sets the value of the 'alert_id' field.
      * @param value The value of 'alert_id'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertId(int value) {
      validate(fields()[0], value);
      this.alert_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_id' field has been set.
      * @return True if the 'alert_id' field has been set, false otherwise.
      */
    public boolean hasAlertId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'alert_id' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_end_time' field.
      * @return The value.
      */
    public long getAlertEndTime() {
      return alert_end_time;
    }


    /**
      * Sets the value of the 'alert_end_time' field.
      * @param value The value of 'alert_end_time'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertEndTime(long value) {
      validate(fields()[1], value);
      this.alert_end_time = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_end_time' field has been set.
      * @return True if the 'alert_end_time' field has been set, false otherwise.
      */
    public boolean hasAlertEndTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'alert_end_time' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertEndTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_start_time' field.
      * @return The value.
      */
    public long getAlertStartTime() {
      return alert_start_time;
    }


    /**
      * Sets the value of the 'alert_start_time' field.
      * @param value The value of 'alert_start_time'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertStartTime(long value) {
      validate(fields()[2], value);
      this.alert_start_time = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_start_time' field has been set.
      * @return True if the 'alert_start_time' field has been set, false otherwise.
      */
    public boolean hasAlertStartTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'alert_start_time' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertStartTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_text' field.
      * @return The value.
      */
    public java.lang.String getAlertText() {
      return alert_text;
    }


    /**
      * Sets the value of the 'alert_text' field.
      * @param value The value of 'alert_text'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertText(java.lang.String value) {
      validate(fields()[3], value);
      this.alert_text = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_text' field has been set.
      * @return True if the 'alert_text' field has been set, false otherwise.
      */
    public boolean hasAlertText() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'alert_text' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertText() {
      alert_text = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_title' field.
      * @return The value.
      */
    public java.lang.String getAlertTitle() {
      return alert_title;
    }


    /**
      * Sets the value of the 'alert_title' field.
      * @param value The value of 'alert_title'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertTitle(java.lang.String value) {
      validate(fields()[4], value);
      this.alert_title = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_title' field has been set.
      * @return True if the 'alert_title' field has been set, false otherwise.
      */
    public boolean hasAlertTitle() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'alert_title' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertTitle() {
      alert_title = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setTimestamp(long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'tracked_entity_id' field.
      * @return The value.
      */
    public int getTrackedEntityId() {
      return tracked_entity_id;
    }


    /**
      * Sets the value of the 'tracked_entity_id' field.
      * @param value The value of 'tracked_entity_id'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setTrackedEntityId(int value) {
      validate(fields()[6], value);
      this.tracked_entity_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'tracked_entity_id' field has been set.
      * @return True if the 'tracked_entity_id' field has been set, false otherwise.
      */
    public boolean hasTrackedEntityId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'tracked_entity_id' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearTrackedEntityId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_level' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.common.Level getAlertLevel() {
      return alert_level;
    }


    /**
      * Sets the value of the 'alert_level' field.
      * @param value The value of 'alert_level'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertLevel(com.aresibo.avro.alert.common.Level value) {
      validate(fields()[7], value);
      this.alert_level = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_level' field has been set.
      * @return True if the 'alert_level' field has been set, false otherwise.
      */
    public boolean hasAlertLevel() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'alert_level' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertLevel() {
      alert_level = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_status' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.common.Status getAlertStatus() {
      return alert_status;
    }


    /**
      * Sets the value of the 'alert_status' field.
      * @param value The value of 'alert_status'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setAlertStatus(com.aresibo.avro.alert.common.Status value) {
      validate(fields()[8], value);
      this.alert_status = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_status' field has been set.
      * @return True if the 'alert_status' field has been set, false otherwise.
      */
    public boolean hasAlertStatus() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'alert_status' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearAlertStatus() {
      alert_status = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.common.Location getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setLocation(com.aresibo.avro.alert.common.Location value) {
      validate(fields()[9], value);
      this.locationBuilder = null;
      this.location = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[9];
    }

    /**
     * Gets the Builder instance for the 'location' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.aresibo.avro.alert.common.Location.Builder getLocationBuilder() {
      if (locationBuilder == null) {
        if (hasLocation()) {
          setLocationBuilder(com.aresibo.avro.alert.common.Location.newBuilder(location));
        } else {
          setLocationBuilder(com.aresibo.avro.alert.common.Location.newBuilder());
        }
      }
      return locationBuilder;
    }

    /**
     * Sets the Builder instance for the 'location' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setLocationBuilder(com.aresibo.avro.alert.common.Location.Builder value) {
      clearLocation();
      locationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'location' field has an active Builder instance
     * @return True if the 'location' field has an active Builder instance
     */
    public boolean hasLocationBuilder() {
      return locationBuilder != null;
    }

    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearLocation() {
      location = null;
      locationBuilder = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'ciram_details' field.
      * @return The value.
      */
    public com.aresibo.avro.alert.risk.CiramDetails getCiramDetails() {
      return ciram_details;
    }


    /**
      * Sets the value of the 'ciram_details' field.
      * @param value The value of 'ciram_details'.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setCiramDetails(com.aresibo.avro.alert.risk.CiramDetails value) {
      validate(fields()[10], value);
      this.ciram_detailsBuilder = null;
      this.ciram_details = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'ciram_details' field has been set.
      * @return True if the 'ciram_details' field has been set, false otherwise.
      */
    public boolean hasCiramDetails() {
      return fieldSetFlags()[10];
    }

    /**
     * Gets the Builder instance for the 'ciram_details' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.aresibo.avro.alert.risk.CiramDetails.Builder getCiramDetailsBuilder() {
      if (ciram_detailsBuilder == null) {
        if (hasCiramDetails()) {
          setCiramDetailsBuilder(com.aresibo.avro.alert.risk.CiramDetails.newBuilder(ciram_details));
        } else {
          setCiramDetailsBuilder(com.aresibo.avro.alert.risk.CiramDetails.newBuilder());
        }
      }
      return ciram_detailsBuilder;
    }

    /**
     * Sets the Builder instance for the 'ciram_details' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder setCiramDetailsBuilder(com.aresibo.avro.alert.risk.CiramDetails.Builder value) {
      clearCiramDetails();
      ciram_detailsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'ciram_details' field has an active Builder instance
     * @return True if the 'ciram_details' field has an active Builder instance
     */
    public boolean hasCiramDetailsBuilder() {
      return ciram_detailsBuilder != null;
    }

    /**
      * Clears the value of the 'ciram_details' field.
      * @return This builder.
      */
    public com.aresibo.avro.alert.risk.RiskAlert.Builder clearCiramDetails() {
      ciram_details = null;
      ciram_detailsBuilder = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RiskAlert build() {
      try {
        RiskAlert record = new RiskAlert();
        record.alert_id = fieldSetFlags()[0] ? this.alert_id : (java.lang.Integer) defaultValue(fields()[0]);
        record.alert_end_time = fieldSetFlags()[1] ? this.alert_end_time : (java.lang.Long) defaultValue(fields()[1]);
        record.alert_start_time = fieldSetFlags()[2] ? this.alert_start_time : (java.lang.Long) defaultValue(fields()[2]);
        record.alert_text = fieldSetFlags()[3] ? this.alert_text : (java.lang.String) defaultValue(fields()[3]);
        record.alert_title = fieldSetFlags()[4] ? this.alert_title : (java.lang.String) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        record.tracked_entity_id = fieldSetFlags()[6] ? this.tracked_entity_id : (java.lang.Integer) defaultValue(fields()[6]);
        record.alert_level = fieldSetFlags()[7] ? this.alert_level : (com.aresibo.avro.alert.common.Level) defaultValue(fields()[7]);
        record.alert_status = fieldSetFlags()[8] ? this.alert_status : (com.aresibo.avro.alert.common.Status) defaultValue(fields()[8]);
        if (locationBuilder != null) {
          try {
            record.location = this.locationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("location"));
            throw e;
          }
        } else {
          record.location = fieldSetFlags()[9] ? this.location : (com.aresibo.avro.alert.common.Location) defaultValue(fields()[9]);
        }
        if (ciram_detailsBuilder != null) {
          try {
            record.ciram_details = this.ciram_detailsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("ciram_details"));
            throw e;
          }
        } else {
          record.ciram_details = fieldSetFlags()[10] ? this.ciram_details : (com.aresibo.avro.alert.risk.CiramDetails) defaultValue(fields()[10]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RiskAlert>
    WRITER$ = (org.apache.avro.io.DatumWriter<RiskAlert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RiskAlert>
    READER$ = (org.apache.avro.io.DatumReader<RiskAlert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.alert_id);

    out.writeLong(this.alert_end_time);

    out.writeLong(this.alert_start_time);

    out.writeString(this.alert_text);

    out.writeString(this.alert_title);

    out.writeLong(this.timestamp);

    out.writeInt(this.tracked_entity_id);

    out.writeEnum(this.alert_level.ordinal());

    out.writeEnum(this.alert_status.ordinal());

    this.location.customEncode(out);

    if (this.ciram_details == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.ciram_details.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.alert_id = in.readInt();

      this.alert_end_time = in.readLong();

      this.alert_start_time = in.readLong();

      this.alert_text = in.readString();

      this.alert_title = in.readString();

      this.timestamp = in.readLong();

      this.tracked_entity_id = in.readInt();

      this.alert_level = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];

      this.alert_status = com.aresibo.avro.alert.common.Status.values()[in.readEnum()];

      if (this.location == null) {
        this.location = new com.aresibo.avro.alert.common.Location();
      }
      this.location.customDecode(in);

      if (in.readIndex() != 1) {
        in.readNull();
        this.ciram_details = null;
      } else {
        if (this.ciram_details == null) {
          this.ciram_details = new com.aresibo.avro.alert.risk.CiramDetails();
        }
        this.ciram_details.customDecode(in);
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.alert_id = in.readInt();
          break;

        case 1:
          this.alert_end_time = in.readLong();
          break;

        case 2:
          this.alert_start_time = in.readLong();
          break;

        case 3:
          this.alert_text = in.readString();
          break;

        case 4:
          this.alert_title = in.readString();
          break;

        case 5:
          this.timestamp = in.readLong();
          break;

        case 6:
          this.tracked_entity_id = in.readInt();
          break;

        case 7:
          this.alert_level = com.aresibo.avro.alert.common.Level.values()[in.readEnum()];
          break;

        case 8:
          this.alert_status = com.aresibo.avro.alert.common.Status.values()[in.readEnum()];
          break;

        case 9:
          if (this.location == null) {
            this.location = new com.aresibo.avro.alert.common.Location();
          }
          this.location.customDecode(in);
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ciram_details = null;
          } else {
            if (this.ciram_details == null) {
              this.ciram_details = new com.aresibo.avro.alert.risk.CiramDetails();
            }
            this.ciram_details.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










